name: PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: PR Review
        uses: team-telnyx/reviewpr@v0.0.2
        with:
          telnyx_api_key: ${{ secrets.TELNYXAI_TOKEN }}
